### ISSUE TITLE
How can I configure arbitrary OAuth providers with additional properties being passed and serialized 

### ISSUE THREAD

**Issue by Bogatinovski** [aguacongas/DymamicAuthProviders#18]
I don't want to use some pre-configured OAuth provider (like GitHub on the sample) and only change the client secret and id. Instead I want to be able to specify all related OAuth configuration settings that are needed like the requested claims, the userinfo endpoint, tokenendpoint etc. 
I already changed the Create  method on HomeController to receive additional user-posted data with the AuthenticationViewModel viewmodel and inside the controller I am creating new OAuthOptions object and populating it. 
```
OAuthOptions oAuthOptions = new OAuthOptions();
oAuthOptions.Scope.Add("openid");
oAuthOptions.Scope.Add("profile");
oAuthOptions.Scope.Add("email");
oAuthOptions.UserInformationEndpoint = "https://mycustomprovider/oauth2/userinfo";
```

Right now the scopes are not saved in the database.

**Comment by aguacongas** [comment]
In witch table are you looking for scope ?

**Comment by Bogatinovski** [comment]
In the Providers table in the SerializedOptions column

**Comment by aguacongas** [comment]
Thanks for reporting this issue, it seems you're right, the serializer doesn't serialize the `OAuthOptions.Scope` property.

You can implement your own `IAuthenticationSchemeOptionsSerializer` based on [`AuthenticationSchemeOptionsSerializer`](https://github.com/aguacongas/DymamicAuthProviders/blob/master/src/Aguacongas.AspNetCore.Authentication/AuthenticationSchemeOptionsSerializer.cs)

And setup the DI to pass your implementation : 
``` csharp
service.AddTransient<IAuthenticationSchemeOptionsSerializer, MyAuthenticationSchemeOptionsSerializer>();
```

**Comment by Bogatinovski** [comment]
I still can't figure out what is the connection between the configuration in the Startup class
`.AddOAuth("Github", "Github", options => {...})` and the new dynamically created configuration through the HomeController.Create method. What is the connection between the two OAuthOptions objects ? Is the one in HomeController overriding some of the properties of the one from the Startup class ?

**Comment by aguacongas** [comment]
The anonymous method `options => {...}` is called each time a new OAuth provider is added to the cache. Either when you load the configuration using `LoadDynamicAuthenticationConfiguration`, or when you add or update a new OAuth configuration. (Update removes the configuration from the cache and adds it).  
So, the code defined in this anonymous method override properties.

**Comment by aguacongas** [comment]
[1.0.0-preview0044](https://github.com/aguacongas/DymamicAuthProviders/releases/tag/1.0.0-preview0044) should fix the `OAuhtOptions.Scope` serialization issue

**Comment by Bogatinovski** [comment]
Thank you for fixing this so quickly!
