### ISSUE TITLE
Issue in generating database

### ISSUE THREAD

**Issue by Goppey** [aguacongas/DymamicAuthProviders#24]
Hi, when I am trying to generate database using the commands given in README.md file it generates error as below:
![Screenshot (99)](https://user-images.githubusercontent.com/13184438/60342699-c857fb80-99cf-11e9-83c3-f26cd85312cd.png)

how can I resolve this issue ?

**Comment by aguacongas** [comment]
Try to reinstall the dotnet core SDK

**Comment by Goppey** [comment]
I have tried that thrice but while searching I found that https://github.com/aspnet/AspNetCore/issues/9822#issuecomment-487586714

But It has been fixed in 3.0.0-preview5 and I am using 3.0.100preview6. Do you think this can be issue for me ?

**Comment by aguacongas** [comment]
Probably

**Comment by Goppey** [comment]
I want to add support for multiple ADFS identity provider. for that:
1) I am adding single **AddOAuth()** in Startup class with some configuration
2) Now on login page when user will add email id and click on next button at that time I want to update OAuthOptions settings like TokenEndpoint, AuthorizationEndpoint, ClientId, ClientSecret etc. based on deciding domain from email id. all these settings will be fetched from db that's already pre-configured from management UI.

Is that possible using this library ?
and Do I need to change my .NET Core > 3.0.0 ?

**Comment by aguacongas** [comment]
No that's not the way the lib should me use, You should register all possible external provider you want to manage and let the user decided witch one she would like to use to login.

The lib is compatible with donet core 3.
