### ISSUE TITLE
Redis cluster not supported

### ISSUE THREAD

**Issue by bearish** [aguacongas/DymamicAuthProviders#42]
**Describe the bug**
When using a redis cluster as the store some operations fails. 

**To Reproduce**
1 setup a redis cluster, the hosted version on Azure can be used
2 configure the connection 
3 try to add multiple providers, change soe of them etc
4 exveptions are thrown 

**Expected behavior**
no eceptions

**Comment by aguacongas** [comment]
@bearish the fix preview is deployed on nuget : https://www.nuget.org/packages/Aguacongas.AspNetCore.Authentication.Redis/3.1.1-preview0017

Can you confirme it's fixed ?
